### ISSUE TITLE
Consider using Github projects

### ISSUE THREAD

**Issue by zeroXten** [owasp-cloud-security/owasp-cloud-security#10]
Looks like it could be a pretty good way of group issue types across a number of Kanban boards.

**Comment by pjbgf** [comment]
I haven't used it before, but it surely looks good. Quite liked the split in the three fronts/projects.

**Comment by zeroXten** [comment]
I haven't used it before either, but so far so good. It would be nice if you could make issues with certain labels automatically appear on the backlog, but it's not a major effort to triage the issues by hand.

**Comment by zeroXten** [comment]
huh. So even closed issues show up on the project. Only option is to remove it from the project or end up with an ever-growing list of done issues.

**Comment by zeroXten** [comment]
Done. Not perfect, but good enough.
