### ISSUE TITLE
EC2 - In a shared tenancy environment, attacker is able to escape their guest VM and influence the instance

### ISSUE THREAD

**Issue by zeroXten** [owasp-cloud-security/owasp-cloud-security#14]

**Comment by zeroXten** [comment]
See https://github.com/owasp-cloud-security/owasp-cloud-security/pull/109

**Comment by paulcutting** [comment]
@zeroXten Does this still need review?  As #109 is merged/

**Comment by zeroXten** [comment]
No. I think there was a bit of duplication because one issue was for reading other guests, and one ones for manipulating, but it probably doesn't make sense to separate them at the feature level.
