### ISSUE TITLE
EC2 - In a shared tenancy environment, attacker is able to read sensitive data through the VM host (e.g. CPU cache)

### ISSUE THREAD

**Issue by zeroXten** [owasp-cloud-security/owasp-cloud-security#15]

**Comment by paulcutting** [comment]
Reviewed https://github.com/owasp-cloud-security/owasp-cloud-security/blob/master/features/aws/ec2/threats/ocst_1_1_1_sensitive_user_data.feature and looks good.

Is there a commit for this?

**Comment by zeroXten** [comment]
This is a specific instance of this threat: https://github.com/owasp-cloud-security/owasp-cloud-security/blob/master/features/aws/ec2/threats/ocst_1_1_7_shared_tenancy_vm_escape.feature

Or at least, it was written as a Meltdown example. More scenarios could extend the scope to other attack types though (like CPU cache).
