### ISSUE TITLE
Create a style guide for threats

### ISSUE THREAD

**Issue by zeroXten** [owasp-cloud-security/owasp-cloud-security#50]

**Comment by zeroXten** [comment]
A Wiki page within the repo would make sense I think.

**Comment by adam234** [comment]
* Can, not may
* Focus on a single threat
* Mitigations are not 1:1 to threats (some mitigations will address multiple threats, some threats will require multiple mitigations to deal with even a first "level" of attack.)

**Comment by zeroXten** [comment]
This information will be transferred over to the BDD styleguide, as part of a threats section.

**Comment by zeroXten** [comment]
See https://github.com/owasp-cloud-security/owasp-cloud-security/wiki/BDD-style-guide
