### ISSUE TITLE
Create a style guide for BDD stories

### ISSUE THREAD

**Issue by zeroXten** [owasp-cloud-security/owasp-cloud-security#51]

**Comment by zeroXten** [comment]
A Wiki page within the repo would make sense I think.

**Comment by paulcutting** [comment]
Starting to work on this, will breakdown into guides on:

- Features
- Feature narrative
- Scenarios
- Given....When....Then formatting

**Comment by paulcutting** [comment]
First few sections complete, @zeroXten please review when you can, as always good to have another pair of eyes on it.

**Comment by zeroXten** [comment]
Looks great! With the move to BDD for the threats, this becomes even more essential. I think we'll need additional sections to document how threats and control stories are written as extracting metadata will depend on threat and control stories following a convention.

**Comment by paulcutting** [comment]
@zeroXten I was about to push an update for Background but you beat me to it :)

I assumed Background was similar to user story use (i.e. further explanation and context) so was going to add this:

### Background
A good title and narrative go along way to explaining a feature, but in more complex situations (as with Agile User stories) a further explanation may be required to provide further context.

For each scenario that requires it simply add a **Background:** followed by a small paragraph of text.

Example:

```
Feature: No sensitive data in user data.
In order to prevent an information disclosure attack
As a Privacy Officer
I want user data to not contain sensitive information, mitigating against OCST-1.1.1


In order to reduce the chances of infrastructure being overloaded by repeated attacks
As an Infrastructure Engineer
I want user data to not contain sensitive information

Background: Any use of sensitive information within a system will make the infrastructure a larger target for attackers.  This in turn will require more infrastructure resources to harden the environments, carry out more pen. tests, etc.
```

**Comment by zeroXten** [comment]
@paulcutting The only caveat is that we will (i think) be using Background as a way of capturing metadata about the threat or control. In BDD then Given When steps are prepended to every scenario so we can use it to set the context. e.g. aws ec2 service.

I think it is good to provide some general information on using Background as long as we are clear about our specific use case.

**Comment by zeroXten** [comment]
From Slack

> The purist in me is starting to think that the Background shouldn't be used in that way (just for metadata). Perhaps the first Given should be `Given an AWS EC2 instance with sensitive information in the User Data attribute`. That does mean though that one would have to write a step that extracts the service and component because it isn't immediately obvious where those values come from. Also, to keep the steps pure I haven't tried to hack it with a catch-all "[x]" step, which also means writing steps for each line, even if they do nothing (just to keep the BDD parser happy).

**Comment by zeroXten** [comment]
So I've ditched using Background for metadata, which means it's freed up for actual BDD use as whoever is writing the story sees fit.

**Comment by paulcutting** [comment]
Added detail for Given When and Then sections.

**Comment by paulcutting** [comment]
@zeroXten What's left to do on this?

**Comment by zeroXten** [comment]
Nothing, it' looks great :) I'll close this issue.
