### ISSUE TITLE
Decide on a versioning and branching strategy for this project

### ISSUE THREAD

**Issue by zeroXten** [owasp-cloud-security/owasp-cloud-security#6]
Options include:

* Keep it agile - no versioning
* Commits and PRs straight to master
* A development branch and feature branches
* Git tagging

**Comment by msaindane** [comment]
Commits straight to master would not be a good idea. There needs to be at least 2 branches. One dev/working branch and one master.

Could use volunteers to review threats submitted before adding it to the master branch.

**Comment by zeroXten** [comment]
Yup, makes sense. Would feature branches be off of the dev branch or master? Do you think it would be worth trying to version things at all (e.g. tagging master)?

**Comment by pjbgf** [comment]
I think that having the master branch protected and only accepting changes by reviewed PRs should do the trick. The timeline would then be tagged at given milestones. This would allow the features to be available as soon as they are reviewed.

**Comment by zeroXten** [comment]
Cool cool. What about versioning? I'm thinking it makes to use something like SemVer as major changes to something like the structure of the threat model YAML files could break compatibility. Should threats and BDD be versioned separately in some way? I'm thinking a major change to either would just bump the major version for the project as a whole.

**Comment by zeroXten** [comment]
In the meantime, I have turned on protected branches for master.

**Comment by zeroXten** [comment]
I'm struggling to see a reason to version. I've time boxed this issue to 2017-10-29, so if there is no particular reason use tagging etc. by then we can just close the issue and revisit later if needed.

**Comment by zeroXten** [comment]
Closing now, as per above, we can revisit if required.
