### ISSUE TITLE
Consider using http://robotframework.org/ as an alternative to BDD

### ISSUE THREAD

**Issue by zeroXten** [owasp-cloud-security/owasp-cloud-security#80]
http://robotframework.org/ as suggested on Twitter https://twitter.com/abhaybhargav/status/927358412949618690

**Comment by zeroXten** [comment]
I've done a bit of reading.Firstly, this really seems to be just a framework, rather than a particular approach or even philosophy. In fact, as it is keyword driven and automatically ignores the BDD keywords (given, then, when) you can use it for BDD stories as well. In which case, anyone could use it as the implementation for the BDD stories in the same way that they could use JBehave or Cucumber.

**Comment by abhaybhargav** [comment]
Yes, thats correct. Its a framework and can be used as an implementation for BDD. The only reason I suggested this was because it is more flexible and I found using this over a pure BDD implementation for Functional/Security tests are much easier todo (personal viewpoint). Have a look at this lib I wrote for OWASP ZAP in the Robot Framework: https://bitbucket.org/we45abhay/robozap

**Comment by zeroXten** [comment]
Very interesting. I can see where you're coming from but I think the flexibility (from an engineering perspective) comes at the cost of communication. As @paulcutting so eloquently puts it in the BDD style guide:

> Feature Narrative
> Using the word narrative, instead of description, emphasises that this should tell a story and therefore > be very similar to a User Story commonly written in Agile Backlogs. 

I feel that the idea of the User Story, and the collaboration that is at the core of the philosophy of BDD, is also core to this project, which was actually created as an OWASP documentation project.

**Comment by zeroXten** [comment]
Very interesting. I can see where you're coming from but I think the flexibility (from an engineering perspective) comes at the cost of communication. As @paulcutting so eloquently puts it in the BDD style guide:

> Feature Narrative
> Using the word narrative, instead of description, emphasises that this should tell a story and therefore > be very similar to a User Story commonly written in Agile Backlogs. 

I feel that the idea of the User Story, and the collaboration that is at the core of the philosophy of BDD, is also core to this project, which was actually created as an OWASP documentation project.

**Comment by zeroXten** [comment]
Very interesting. I can see where you're coming from but I think the flexibility (from an engineering perspective) comes at the cost of communication. As @paulcutting so eloquently puts it in the BDD style guide:

> Feature Narrative
> Using the word narrative, instead of description, emphasises that this should tell a story and therefore > be very similar to a User Story commonly written in Agile Backlogs. 

I feel that the idea of the User Story, and the collaboration that is at the core of the philosophy of BDD, is also core to this project, which was actually created as an OWASP documentation project.

**Comment by zeroXten** [comment]
Going to close this one because people can use Robot Framework as the implementation if they wish.
