### ISSUE TITLE
Explore the idea of using personas to enrich the stories

### ISSUE THREAD

**Issue by zeroXten** [owasp-cloud-security/owasp-cloud-security#82]
Awesome example of personas being used for Tails: https://tails.boum.org/blueprint/personas/

I'm thinking there would probably be only one attacker persona (attribution is hard), but control stories could have for example

* Engineer
* Auditor
* Security consultant
* Risk owner
* GDPR stuff like Data Subject and Data Processor

These personas would then be used in the BDD stories in the "As a ......" feature narratives.

**Comment by paulcutting** [comment]
Nice, definitely good to have these as a guide.

**Comment by zeroXten** [comment]
See https://github.com/owasp-cloud-security/owasp-cloud-security/wiki/BDD-personas
